# Generated by Django 6.0.1 on 2026-01-07 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'forms_builder_formtemplate',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('email', 'Email'), ('password', 'Password'), ('date', 'Date'), ('textarea', 'Text Area'), ('select', 'Select/Dropdown'), ('checkbox', 'Checkbox'), ('file', 'File Upload')], default='text', max_length=50)),
                ('placeholder', models.CharField(blank=True, max_length=255, null=True)),
                ('options', models.JSONField(blank=True, help_text='For select fields, store options as JSON array', null=True)),
                ('required', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('form_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='forms_builder.formtemplate')),
            ],
            options={
                'db_table': 'forms_builder_formfield',
                'ordering': ['order'],
            },
        ),
    ]
